name: New Release
permissions:
  contents: write
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true
jobs:
  release:
    runs-on: macos-latest
    env:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Debug Token
        run: |
          if [ -z "${{ secrets.PAT_TOKEN }}" ]; then
            echo "PAT_TOKEN secret is empty or not set!"
          else
            echo "PAT_TOKEN secret exists (length: ${#PAT_TOKEN})"
          fi
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Create Git Tag
        run: |
          VERSION='${{ github.event.inputs.version }}'
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "TAG=v$VERSION" >> $GITHUB_ENV
          if [ -f changelog.md ]; then
            CHANGELOG=$(cat changelog.md)
          else
            CHANGELOG="No release notes provided."
          fi
          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
          echo "$CHANGELOG" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          
          git config user.name "netcaps-bot"
          git config user.email "bot@users.noreply.github.com"
          git tag -a "v$VERSION" -m "Version $VERSION"
          git push origin "v$VERSION"

      - name: Get Source Code sha256
        run: |
          git archive --format=tar.gz --prefix="netcaps-${{ env.VERSION }}/" HEAD > netcaps-${{ env.VERSION }}-src.tar.gz
          SHA256=$(shasum -a 256 netcaps-${{ env.VERSION }}-src.tar.gz | cut -d ' ' -f 1)
          echo "SHA256=$SHA256" >> $GITHUB_ENV

      - name: Build Binary Tarball
        run: |
          swift build -c release --disable-sandbox
          mv .build/release/netcaps netcaps
          tar -czf netcaps-${{ env.VERSION }}-macos-arm64.tar.gz netcaps

      - name: Push Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG }}
          name: "Version ${{ env.VERSION }}"
          body: ${{ env.CHANGELOG }}
          files: |
            netcaps-${{ env.VERSION }}-macos-arm64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Homebrew Tap
      	env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git clone https://x-access-token:${PAT_TOKEN}@github.com/forcequitOS/homebrew-brew tap
          cd tap
          sed -i.bak \
            -e "s|url \".*\"|url \"https://github.com/forcequitOS/netcaps/archive/refs/tags/${{ env.TAG }}.tar.gz\"|" \
            -e "s|sha256 \".*\"|sha256 \"${{ env.SHA256 }}\"|" \
            -e "s|version \".*\"|version \"${{ env.VERSION }}\"|" \
            netcaps.rb
          git config user.name "netcaps-bot"
          git config user.email "bot@users.noreply.github.com"
          git add netcaps.rb
          git commit -m "netcaps ${{ env.VERSION }}"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}